name: Scheduled Link Check

on:
  schedule:
    - cron: "00 19 * * *"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      site_git_ref:
        description: 'git ref, a SHA commit or branch or tag, for the published HTML content'
        required: true
        default: 'nist-pages'
        type: string
      site_git_ref_path:
        description: 'the subdirectory to check out git ref and check links in website content'
        required: true
        default: 'published'
        type: string
jobs:
  schedule-validate-repo-markdown-links:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
    with:
      createIssue: true
  schedule-validate-website-links:
    uses: ./.github/workflows/workflow-validate-website-content.yml
    with:
      createIssue: true
