name: Scheduled Link Check

on:
  schedule:
    - cron: "00 19 * * *"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ignorePattern:
        description: 'a pattern provided to grep for files/directories to ignore'
        required: false
        default: '^docs/'
        type: string
      markdownLinkCheckConfig:
        description: 'the path to the markdown link check config file'
        required: false
        default: 'build/config/.markdown-link-check/config.json'
        type: string
      site_git_ref:
        description: 'git ref, a SHA commit or branch or tag, for the published HTML content'
        required: true
        default: 'nist-pages'
        type: string
      site_git_ref_path:
        description: 'the subdirectory to check out git ref and check links in website content'
        required: true
        default: 'published'
        type: string
jobs:
  schedule-validate-repo-markdown-links:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
    if: github.event_name != 'workflow_dispatch'
    with:
      ignorePattern: '^docs/'
      markdownLinkCheckConfig: 'build/config/.markdown-link-check/config.json'
      createIssue: true
  schedule-validate-repo-markdown-links-debug:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      ignorePattern: ${{ github.event.inputs.ignorePattern }}
      markdownLinkCheckConfig: ${{ github.event.inputs.markdownLinkCheckConfig }}
      createIssue: true
  schedule-validate-website-links:
    uses: ./.github/workflows/workflow-validate-website-content.yml
    if: github.event_name != 'workflow_dispatch'
    with:
      site_git_ref: 'nist-pages'
      site_git_ref_path: 'published'
      createIssue: true
  schedule-validate-website-links-debug:
    uses: ./.github/workflows/workflow-validate-website-content.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      site_git_ref: ${{ github.event.inputs.site_git_ref }}
      site_git_ref_path: ${{ github.event.inputs.site_git_ref_path }}
      createIssue: true
  create-issues:
    steps:
    - name: Create issue if bad links detected in repo
      #if: failure() && (github.event.inputs.createIssue == 'true' || inputs.createIssue == true)
      if: jobs.schedule-validate-website-links.linkcheck.outcome == 'failure'
      uses: peter-evans/create-issue-from-file@97e6f902a416aac38834e23fa52e166aad0437d2 # v3.0.0
      with:
        title: Scheduled Check of Markdown Documents Found Bad Hyperlinks
        content-filepath: mlc_report.log
        labels: bug